### PR TITLE
REST

### PR DESCRIPTION
**Pull request by vladfr**
Hello!

I thought I'd give it a go.

This also fixes several stuff in base classes:
 - states could not have more than 1 transition (bug caused it to override)
 - exit step was not executed (now executes in catch)
 - entry and exit criteria are not required, they return true in abstract
 - logging class names

### CODE REVIEW

**Comment by mihai-stancu** [comment]
Allright! Way to digg in!

**Comment by mihai-stancu** [comment]
APIs are a good example model, the have well known states.

What other good real life examples could we use to help us figure out what needs to be formalized and how to formalize it?

**Comment by mihai-stancu** [comment]
High-level / business-overview of ecommerce order process for automated systems like amazon & emag?

* Order placed
  - Order validated
  - Stock reserved
  - Order persisted
* Order invoiced
  - Discounts processed
  - Cash received /or/ Transfer received /or/  CC charged /or/ Cash on delivery
  - Accounting ledger updated
*  Order picked & packaged in warehouse
  - ...
*  Delivery handed over to courier
  - AWB registered

**Comment by vladfr** [comment]
I was thinking about the need to extend/override simpler processes to
create more complex ones. Like CRUD->order. Would a crud even work?

**Comment by mihai-stancu** [comment]
I don't know about Process extensibility/reusability i thought about them
as application dedicated classes like controllers.

States will be used/reused across the current app -- a cron can make take a
payload from state10 to state 15 and a controller could take it from
state12 to state 20.

State (as process nodes) can have like their own subprocess and their own
state graph.

Reusing groups of states across applications could be feasible if they
represent a subgraph of your graph.

The other way round may be tricky because like inheritance not all
functions/methods can be overridden so replacing the entire base class
with your extension class would require dependency injection.

**Pull request merged**
